/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ovs;

import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author CHINTAN
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(tk.getScreenSize().width, tk.getScreenSize().height);
        mPartyList.setVisible(false);
        mStart.setVisible(false);
        mShowResult.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mShowResult = new javax.swing.JTextArea();
        mStart = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mPartyList = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome! Admin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 10, 1070, 112);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/exit_to_app_white_48x48.png"))); // NOI18N
        jLabel4.setText("LOG OUT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1430, 50, 100, 70);

        mResult.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        mResult.setForeground(new java.awt.Color(255, 255, 255));
        mResult.setText("Compute Results");
        mResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mResultMouseClicked(evt);
            }
        });
        getContentPane().add(mResult);
        mResult.setBounds(980, 280, 300, 40);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Election");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 280, 240, 40);

        mShowResult.setEditable(false);
        mShowResult.setColumns(20);
        mShowResult.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        mShowResult.setRows(5);
        jScrollPane1.setViewportView(mShowResult);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(980, 360, 480, 270);

        mStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/8788803-designstyle-sale-m.png"))); // NOI18N
        mStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mStartMouseClicked(evt);
            }
        });
        getContentPane().add(mStart);
        mStart.setBounds(120, 660, 300, 50);

        mPartyList.setColumns(20);
        mPartyList.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        mPartyList.setRows(5);
        mPartyList.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(mPartyList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(120, 360, 450, 270);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(980, 660, 270, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/Nice-Dark-Gradient.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1720, 1140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        StartScreen s = new StartScreen();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        mPartyList.setVisible(true);
        mStart.setVisible(true);
        jScrollPane2.setVisible(true);
        mShowResult.setVisible(false);
        jScrollPane1.setVisible(false);
        mPartyList.requestFocus();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void mStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mStartMouseClicked
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
            Statement st = conn.createStatement();
            st.execute("truncate election_candidates");
            PreparedStatement ps = conn.prepareStatement("Insert into election_candidates(name,votes) values (?,?)");
            for (String line : mPartyList.getText().split("\\n")) 
            if(!line.isEmpty())
            {
                ps.setString(1, line);
                ps.setString(2,"0");
                ps.execute();
            }
            
            st.execute("Update registered_users set vote='0' ");
            
            JOptionPane.showMessageDialog(new Frame("Admin"),"Election has been successfully started.","Election",JOptionPane.PLAIN_MESSAGE);
            mPartyList.setVisible(false);
            mStart.setVisible(false);
            jScrollPane2.setVisible(false);
            mPartyList.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(new Frame("Admin"),"Error Occured!.","Election",JOptionPane.ERROR_MESSAGE);
        }
                
        
    }//GEN-LAST:event_mStartMouseClicked

    private void mResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mResultMouseClicked
        try {
            // TODO add your handling code here:
            
            mShowResult.setVisible(true);
            jScrollPane1.setVisible(true);
            mPartyList.setVisible(false);
            mStart.setVisible(false);
            jScrollPane2.setVisible(false);
            mShowResult.setText("Name\tVotes\n_____________________\n\n");
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from election_candidates order by votes desc");
            
            while(rs.next()){
                mShowResult.setText(mShowResult.getText()+rs.getString("name")+"\t"+rs.getString("votes")+"\n");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mPartyList;
    private javax.swing.JLabel mResult;
    private javax.swing.JTextArea mShowResult;
    private javax.swing.JLabel mStart;
    // End of variables declaration//GEN-END:variables
}
