/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ovs;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;

/**
 *
 * @author CHINTAN
 */
public class EditInfo extends javax.swing.JFrame {

    /**
     * Creates new form EditInfo
     */
    public String AadharNo,Username,Password,Email,MobileNo,tPassword=null;
    
    public EditInfo() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(tk.getScreenSize().width, tk.getScreenSize().height);
        mEmail.setUI(new HintTextFieldUI("Email", Color.GRAY));
        mUsername.setUI(new HintTextFieldUI("Name", Color.GRAY));
        mMobileNo.setUI(new HintTextFieldUI("Mobile No.", Color.GRAY));
        mPassword.setUI(new HintTextFieldUI("Password", Color.GRAY));
    }
    
    public EditInfo(String s){
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(tk.getScreenSize().width, tk.getScreenSize().height);
        mEmail.setUI(new HintTextFieldUI("Email", Color.GRAY));
        mUsername.setUI(new HintTextFieldUI("Name", Color.GRAY));
        mMobileNo.setUI(new HintTextFieldUI("Mobile No.", Color.GRAY));
        mPassword.setUI(new HintTextFieldUI("Password", Color.GRAY));
        AadharNo=s;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mEmail = new javax.swing.JTextField();
        mUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mMobileNo = new javax.swing.JTextField();
        mPassword = new javax.swing.JTextField();
        mSaveButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        mEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        mEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(mEmail);
        mEmail.setBounds(600, 230, 420, 60);

        mUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        mUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(mUsername);
        mUsername.setBounds(600, 320, 420, 60);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 30, 1250, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHINTAN\\Downloads\\arrow_back_white_36x36.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 40, 70, 70);

        mMobileNo.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        mMobileNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(mMobileNo);
        mMobileNo.setBounds(600, 410, 420, 60);

        mPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        mPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(mPassword);
        mPassword.setBounds(600, 500, 420, 60);

        mSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/8782884-designstyle-sale-l.png"))); // NOI18N
        mSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSaveButtonMouseClicked(evt);
            }
        });
        getContentPane().add(mSaveButton);
        mSaveButton.setBounds(670, 600, 300, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/Nice-Dark-Gradient.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 2390, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jLabel1.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    public boolean checkAadharno(String ad){
        if(ad.length() != 12)
               return false;
        for(int i = 0;i < ad.length();++i)
        {
            char c = ad.charAt(i);
            if(!(c >= '0' && c <= '9'))
                return false;
        }
        return true;
    }
    
    public boolean checkMobileno(String ad){
        if(ad.length() != 10)
               return false;
        for(int i = 0;i < ad.length();++i)
        {
            char c = ad.charAt(i);
            if(!(c >= '0' && c <= '9'))
                return false;
        }
        return true;
    }
    public void Reset(){
        mPassword.setText("");
        mUsername.setText("");
        mMobileNo.setText("");
        mEmail.setText("");
      
    }
    private void mSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSaveButtonMouseClicked
        // TODO add your handling code here:
        Email = mEmail.getText();
        MobileNo = mMobileNo.getText();
        Username = mUsername.getText();
        Password = mPassword.getText();
      //  boolean flag=false;
        if(!Email.isEmpty() && !MobileNo.isEmpty() && !Username.isEmpty() && !Password.isEmpty() && checkAadharno(AadharNo) && checkMobileno(MobileNo)){
            
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                PreparedStatement ps = conn.prepareStatement("Update registered_users set email=? , password=? , mobile_no=? ,username=?  where aadhar_no=?");
                
                ps.setString(1, Email);
                ps.setString(2, Password);
                ps.setString(3, MobileNo);
                ps.setString(4, Username);
                ps.setString(5, AadharNo);
                ps.execute();
                JOptionPane.showMessageDialog(new Frame("Account Created"),"Update Successfull !","Update",PLAIN_MESSAGE);
           
                this.dispose();
                } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(EditInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
               
        }
        else
          JOptionPane.showMessageDialog(new Frame("Invalid Entry"),"Enter valid values in the fields.");
        
        
    }//GEN-LAST:event_mSaveButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mEmail;
    private javax.swing.JTextField mMobileNo;
    private javax.swing.JTextField mPassword;
    private javax.swing.JLabel mSaveButton;
    private javax.swing.JTextField mUsername;
    // End of variables declaration//GEN-END:variables
}
