/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ovs;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author CHINTAN
 */



public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public String Aadharno,Password,tPassword;
    
    public StartScreen() {
        initComponents();
        mAadharno.setUI(new HintTextFieldUI("Aadhar No.", Color.GRAY));
        mPassword.setUI(new HintTextFieldUI("Password",Color.GRAY));
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(tk.getScreenSize().width, tk.getScreenSize().height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        mAadharno = new javax.swing.JTextField();
        mLogin = new javax.swing.JLabel();
        mNewUser = new javax.swing.JLabel();
        mUserchk = new javax.swing.JRadioButton();
        mAdminchk = new javax.swing.JRadioButton();
        mPassword = new javax.swing.JTextField();
        mForgotPassword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OVS");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 72)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ONLINE VOTING SYSTEM");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-150, 70, 1920, 112);

        mAadharno.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        mAadharno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(mAadharno);
        mAadharno.setBounds(590, 370, 420, 60);

        mLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHINTAN\\Downloads\\8778900-designstyle-sale-m.png")); // NOI18N
        mLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mLoginMouseClicked(evt);
            }
        });
        getContentPane().add(mLogin);
        mLogin.setBounds(660, 600, 300, 50);

        mNewUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mNewUser.setForeground(java.awt.Color.white);
        mNewUser.setText("Not yet registered ? Click Here.");
        mNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mNewUserMouseClicked(evt);
            }
        });
        getContentPane().add(mNewUser);
        mNewUser.setBounds(620, 700, 380, 30);

        mUserchk.setBackground(getBackground());
        mUserchk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mUserchk.setForeground(java.awt.Color.white);
        mUserchk.setSelected(true);
        mUserchk.setText("User");
        mUserchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserchkActionPerformed(evt);
            }
        });
        getContentPane().add(mUserchk);
        mUserchk.setBounds(610, 530, 140, 40);

        mAdminchk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mAdminchk.setForeground(java.awt.Color.white);
        mAdminchk.setText("Admin");
        mAdminchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAdminchkActionPerformed(evt);
            }
        });
        getContentPane().add(mAdminchk);
        mAdminchk.setBounds(820, 530, 140, 40);

        mPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        mPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPasswordActionPerformed(evt);
            }
        });
        mPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(mPassword);
        mPassword.setBounds(590, 450, 420, 60);

        mForgotPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mForgotPassword.setForeground(java.awt.Color.white);
        mForgotPassword.setText("Forgot Password ?");
        mForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mForgotPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(mForgotPassword);
        mForgotPassword.setBounds(690, 750, 230, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/colorful-triangles-background_yB0qTG6.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 2240, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLoginMouseClicked
        // TODO add your handling code here:
        /*&this.dispose();
        UserLogin Ul = new UserLogin();
        Ul.setVisible(true);*/
        Aadharno = mAadharno.getText();     
        
        if(Aadharno.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(new Frame(), "Please enter Aadhar No. and Password.","LogIn",JOptionPane.INFORMATION_MESSAGE);
        }     
        else{
            if(mUserchk.isSelected()){
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("Select * from registered_users");
                    boolean flag = true;
                    while(rs.next()){
                      
                        if(Aadharno.equals(rs.getString("aadhar_no")) && Password.equals(rs.getString("password")))
                        {
                            flag = false;
                            UserLogin ul = new UserLogin(rs.getString("username"),rs.getString("aadhar_no"),rs.getString("email"),rs.getString("mobile_no"),rs.getBoolean("vote"));
                            ul.setVisible(true);
                            this.dispose();
                        }
                    }
                    if(flag)
                    {
                         JOptionPane.showMessageDialog(new Frame(), "Incorrect Aadhar No or Password.","LogIn",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(StartScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(mAdminchk.isSelected()){
                
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("Select * from registered_admin");
                    boolean flag = true;
                    while(rs.next()){
                       
                        if(Aadharno.equals(rs.getString("aadhar_no")) && Password.equals(rs.getString("password")))
                        {
                            flag = false;
                            AdminLogin ul = new AdminLogin();
                            ul.setVisible(true);
                            this.dispose();
                        }
                    }
                    if(flag)
                    {
                         JOptionPane.showMessageDialog(new Frame(), "Incorrect Aadhar No or Password.","LogIn",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(StartScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
             }
        }
        
     //
        
        
    }//GEN-LAST:event_mLoginMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        mLogin.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void mNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mNewUserMouseClicked
        // TODO add your handling code here:
       
        NewVoter Ul = new NewVoter();
        Ul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mNewUserMouseClicked

    private void mUserchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserchkActionPerformed
        // TODO add your handling code here:
        mAdminchk.setSelected(false);
    }//GEN-LAST:event_mUserchkActionPerformed

    private void mAdminchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAdminchkActionPerformed
        // TODO add your handling code here:
        mUserchk.setSelected(false);
    }//GEN-LAST:event_mAdminchkActionPerformed

    private void mPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPasswordActionPerformed

    private void mPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mPasswordKeyReleased
        // TODO add your handling code here:
        String temp = null ;
        char c = evt.getKeyChar();
        if(c == evt.VK_ENTER){
            
            Aadharno = mAadharno.getText();     
        
        if(Aadharno.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(new Frame(), "Please enter Aadhar No. and Password.","LogIn",JOptionPane.INFORMATION_MESSAGE);
        }     
        else{
            if(mUserchk.isSelected()){
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("Select * from registered_users");
                    boolean flag = true;
                    while(rs.next()){
                      
                        if(Aadharno.equals(rs.getString("aadhar_no")) && Password.equals(rs.getString("password")))
                        {
                            flag = false;
                            UserLogin ul = new UserLogin(rs.getString("username"),rs.getString("aadhar_no"),rs.getString("email"),rs.getString("mobile_no"),rs.getBoolean("vote"));
                            ul.setVisible(true);
                            this.dispose();
                        }
                    }
                    if(flag)
                    {
                         JOptionPane.showMessageDialog(new Frame(), "Incorrect Aadhar No or Password.","LogIn",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(StartScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(mAdminchk.isSelected()){
                
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("Select * from registered_admin");
                    boolean flag = true;
                    while(rs.next()){
                       
                        if(Aadharno.equals(rs.getString("aadhar_no")) && Password.equals(rs.getString("password")))
                        {
                            flag = false;
                            AdminLogin ul = new AdminLogin();
                            ul.setVisible(true);
                            this.dispose();
                        }
                    }
                    if(flag)
                    {
                         JOptionPane.showMessageDialog(new Frame(), "Incorrect Aadhar No or Password.","LogIn",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(StartScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
             }
        }
        
            
        }
        if(c == evt.VK_BACK_SPACE)
        {
           if(!tPassword.isEmpty())
                    tPassword = tPassword.substring(0, tPassword.length() - 1);
           //temp = temp.substring(0,temp.length()-1);
        }
        else{
                if(tPassword == null)
                    tPassword = ""+c;
                else
                    tPassword += c;
            //temp = temp.substring(0,temp.length()-1);
         //   temp += '*';          
        }
        if(tPassword.isEmpty())
            mPassword.setText("");
        else{
            temp = ""+'*';
            int l = tPassword.length();
            while(l-- > 1)
                temp += '*';
            mPassword.setText(temp);
        }
        Password = tPassword;
       // System.out.println(Password);
    }//GEN-LAST:event_mPasswordKeyReleased

    private void mPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mPasswordKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_mPasswordKeyTyped

    public void sendPassword(String Email,String id) throws AddressException, MessagingException{
        String host = "smtp.gmail.com";
        String user = "santynit2015@gmail.com";
        String pass = "santynit";
        String to = Email;
        String from = "cj.djsaini@gmail.com";
        String subject = "Forgot Password";
        
        String message = "Your password for OVS account is "+id;
        boolean sessionDebug = false;
        Properties props = System.getProperties();
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.host",host);
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.port","587");
        props.put("mail.smtp.starttls.required","true");
        
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(props,null);
        mailSession.setDebug(sessionDebug);
        Message msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(from));
        InternetAddress address = (new InternetAddress(to));
        msg.setRecipient(Message.RecipientType.TO, address);
        msg.setSubject(subject);
        msg.setText(message);
        
        Transport transport = mailSession.getTransport("smtp");
        transport.connect(host,user,pass);
        transport.sendMessage(msg, msg.getAllRecipients());
        transport.close();
    }
    
    
    private void mForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mForgotPasswordMouseClicked
        // TODO add your handling code here:
        
        Aadharno = JOptionPane.showInputDialog(new Frame("Password"),"Enter your Aadhar No.","Forgot Password", JOptionPane.QUESTION_MESSAGE);
        
        if(Aadharno != null){
        try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("Select * from registered_users");
                    boolean flag = true;
                    while(rs.next()){
                      
                        if(Aadharno.equals(rs.getString("aadhar_no")))
                        {
                            flag = false;
                            JOptionPane.showMessageDialog(new Frame(), "Password has been sent to registered Email Address.","Password",JOptionPane.INFORMATION_MESSAGE);
                            sendPassword(rs.getString("email"),rs.getString("password"));
                        }
                    }
                    if(flag)
                    {
                         JOptionPane.showMessageDialog(new Frame(), "Aadhar No. not registered.","Password",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException | SQLException | MessagingException ex) {
                    Logger.getLogger(StartScreen.class.getName()).log(Level.SEVERE, null, ex);
                }     
        }
    }//GEN-LAST:event_mForgotPasswordMouseClicked

    private void mPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mPasswordKeyPressed
        // TODO add your handling code here:
       char c = evt.getKeyChar();
       if(c == KeyEvent.VK_BACK_SPACE){
           tPassword ="";
           Password ="";
           mPassword.setText("");
       }
    }//GEN-LAST:event_mPasswordKeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        mLogin.requestFocus();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mAadharno;
    private javax.swing.JRadioButton mAdminchk;
    private javax.swing.JLabel mForgotPassword;
    private javax.swing.JLabel mLogin;
    private javax.swing.JLabel mNewUser;
    private javax.swing.JTextField mPassword;
    private javax.swing.JRadioButton mUserchk;
    // End of variables declaration//GEN-END:variables
}
