/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ovs;

import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author CHINTAN
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public String Username,Aadharno,Email,MobileNo;
    public Boolean Vote;
    public String ev;
    public UserLogin(String u,String a,String e,String m,Boolean v) throws SQLException {
        try {
            Username = u;
            Aadharno = a;
            Email = e;
            MobileNo = m;
            Vote = v;
            initComponents();
            Toolkit tk = Toolkit.getDefaultToolkit();
            this.setSize(tk.getScreenSize().width, tk.getScreenSize().height);
            jLabel3.setText(jLabel3.getText() + " " + u);
            mLabelOTP.setVisible(false);
            mTextOTP.setVisible(false);
            mButtonOTP.setVisible(false);
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from election_candidates");
            while(rs.next())
            {
                mCandidateList.addItem(rs.getString("name"));
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public UserLogin(){
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(tk.getScreenSize().width, tk.getScreenSize().height);
        mLabelOTP.setVisible(false);
        mTextOTP.setVisible(false);
        mButtonOTP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        mCandidateList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        mButtonOTP = new javax.swing.JButton();
        mLabelOTP = new javax.swing.JLabel();
        mTextOTP = new javax.swing.JTextField();
        mVote = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 40, 1070, 112);

        mCandidateList.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        getContentPane().add(mCandidateList);
        mCandidateList.setBounds(100, 340, 310, 50);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select a candidate ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 280, 350, 40);

        mButtonOTP.setBackground(new java.awt.Color(255, 255, 255));
        mButtonOTP.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        mButtonOTP.setText("SUBMIT");
        mButtonOTP.setBorder(null);
        mButtonOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonOTPActionPerformed(evt);
            }
        });
        getContentPane().add(mButtonOTP);
        mButtonOTP.setBounds(490, 550, 200, 50);

        mLabelOTP.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        mLabelOTP.setForeground(new java.awt.Color(255, 255, 255));
        mLabelOTP.setText("Enter OTP");
        getContentPane().add(mLabelOTP);
        mLabelOTP.setBounds(100, 550, 190, 50);

        mTextOTP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mTextOTP);
        mTextOTP.setBounds(320, 550, 140, 50);

        mVote.setBackground(new java.awt.Color(255, 255, 255));
        mVote.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        mVote.setText("VOTE");
        mVote.setBorder(null);
        mVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVoteActionPerformed(evt);
            }
        });
        getContentPane().add(mVote);
        mVote.setBounds(100, 410, 120, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/exit_to_app_white_48x48.png"))); // NOI18N
        jLabel4.setText("LOG OUT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1430, 50, 100, 70);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Edit Profile");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1180, 280, 230, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ovs/Nice-Dark-Gradient.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1800, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        EditInfo e = new EditInfo(Aadharno);
        e.setVisible(true);
       // this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        StartScreen s = new StartScreen();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    String emailVerify() throws AddressException, MessagingException{
        String host = "smtp.gmail.com";
        String user = "santynit2015@gmail.com";
        String pass =  "santynit";
        String to = Email;
        String from = "cj.djsaini@gmail.com";
        String subject = "Voting Process";
        
        Random rand = new Random();
        String id = String.format("%04d", rand.nextInt(10000));
        
        String message = "Your OTP for Voting Process is "+id;
        boolean sessionDebug = false;
        Properties props = System.getProperties();
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.host",host);
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.port","587");
        props.put("mail.smtp.starttls.required","true");
        
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(props,null);
        mailSession.setDebug(sessionDebug);
        Message msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(from));
        InternetAddress address = (new InternetAddress(to));
        msg.setRecipient(Message.RecipientType.TO, address);
        msg.setSubject(subject);
        msg.setText(message);
        
        Transport transport = mailSession.getTransport("smtp");
        transport.connect(host,user,pass);
        transport.sendMessage(msg, msg.getAllRecipients());
        transport.close();
        return id;
    }
        
    
    private void mVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVoteActionPerformed
        // TODO add your handling code here:
        if(!Vote){ 
        try {
                  ev = emailVerify();
                } catch (MessagingException ex) {
                    JOptionPane.showMessageDialog(new Frame("Invalid Email"),"Invalid Email Address","Email Verification",JOptionPane.ERROR_MESSAGE);
                }
        
        mLabelOTP.setVisible(true);
        mTextOTP.setVisible(true);
        mButtonOTP.setVisible(true);
        mTextOTP.requestFocus();
        }
        else{
             JOptionPane.showMessageDialog(new Frame("Invalid Email"),"Already voted.","Vote",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_mVoteActionPerformed

    private void mButtonOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonOTPActionPerformed
        // TODO add your handling code here:
        if(ev.equals(mTextOTP.getText())){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs", "root", "root");
                PreparedStatement st = conn.prepareStatement("Select * from election_candidates where name=?");
                String choice = (String) mCandidateList.getSelectedItem();
                st.setString(1, choice);
                ResultSet rs =st.executeQuery();
                rs.next();
                long votes = Long.parseLong(rs.getString("votes"));
                votes++;
                st = conn.prepareStatement("Update election_candidates set votes=? where name=?");
                st.setString(1, String.valueOf(votes));
                st.setString(2, (choice));
                st.execute();
                JOptionPane.showMessageDialog(new Frame("Invalid Email"),"Successfully voted to "+choice,"Vote",JOptionPane.INFORMATION_MESSAGE);
                Vote = true;
                st = conn.prepareStatement("Update registered_users set vote ='1' where aadhar_no=?");
                st.setString(1,Aadharno);
                st.execute();
                
                mLabelOTP.setVisible(false);
                mTextOTP.setVisible(false);
                mButtonOTP.setVisible(false);
                
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mButtonOTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton mButtonOTP;
    private javax.swing.JComboBox<String> mCandidateList;
    private javax.swing.JLabel mLabelOTP;
    private javax.swing.JTextField mTextOTP;
    private javax.swing.JButton mVote;
    // End of variables declaration//GEN-END:variables
}
